resource_list = [
  {
    "name": "1ES Resource Management PPE",
    "appDn": "c",
    "appId": "9fc8264d-0a40-4790-86e1-e7b73a2d2298",
    "p_type": "oa",
    "p_atype": "manage",
    "p": "manage_ado_pools",
    "p_id": "99c58aeb-f6a2-4999-b722-b052dc773c26",
    "p_fam": "manage_ado_pools",
    "oa_aCsDn": "Manage AzDevops Pools",
    "oa_aCsDc": "This allows users to manage ADO Pools. ",
    "oa_uCsDn": "c",
    "oa_uCsDc": "This allows Manage AzDevops Pools",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Access IoT Hub Device Provisioning Service",
    "appDn": "c",
    "appId": "0cd79364-7a90-4354-9984-6e36c841418d",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "02ce5515-6df6-47e3-b3a5-96dd4fc74f64",
    "p_fam": None,
    "oa_aCsDn": "Access to IoT DPS",
    "oa_aCsDc": "Access to IoT DPS",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "AIO-Diagnostics-Admin-Service-App",
    "appDn": "c",
    "appId": "31fdbf2a-d670-4e19-8d36-595a1333c3c3",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Tokens.Get",
    "p_id": "7a4930f3-f625-4ed4-a257-5cdb1401acb9",
    "p_fam": "Tokens",
    "oa_aCsDn": "Generate SAS Token.",
    "oa_aCsDc": "Allows user to generate a sas token.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "App Protection",
    "appDn": "c",
    "appId": "c6e44401-4d0a-4542-ab22-ecd4c90d28d7",
    "p_type": "oa",
    "p_atype": "read",
    "p": "usage.read.all",
    "p_id": "c9742cae-d7c1-4b54-a641-5f676846a768",
    "p_fam": "usage",
    "oa_aCsDn": "usage.read.all",
    "oa_aCsDc": "this allows user to read app usage in the organization. Requires admin consent",
    "oa_uCsDn": "c",
    "oa_uCsDc": "this allows user to read app usage in the organization",
    "csReq": "t",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Application Insights API",
    "appId": "f5c26e74-f226-4ae8-85f0-b4af0080ac9e",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Data.Read",
    "p_id": "3c63f9fe-1706-42a7-9f53-25b47753d668",
    "p_fam": "Data",
    "ar_dn": "Read Application Insights Data",
    "ar_dc": "Allow this application to access Application Insights data",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Attestation Service",
    "appId": "c61423b7-1d1f-430d-b444-0eee53298103",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "aabdcc35-2d84-4cae-b8f0-23d8272e3fec",
    "p_fam": None,
    "ar_dn": "user_impersonation",
    "ar_dc": "Default permission to access Attestation service",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Autonomous Development Platform",
    "appDn": "c",
    "appId": "150c8903-2280-4ab6-8708-b080044d94c6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "bd7d1ce5-f0a9-4489-a4df-3e41e7b963e2",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Autonomous Development Platform",
    "oa_aCsDc": "Allow the application to access Azure Autonomous Development Platform on behalf of the signed-in user.",
    "oa_uCsDn": "Access Azure Autonomous Development Platform as the Signed-in User",
    "oa_uCsDc": "Allow the application to access Azure Autonomous Development Platform on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure AD Identity Governance Insights",
    "appId": "58c746b0-a0b0-4647-a8f6-12dde5981638",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Insights.Read.AccessRecommendation",
    "p_id": "179ad82c-ddf7-4180-9ecc-af2608f2ae6d",
    "p_fam": "Insights",
    "ar_dn": "Read access recommendation insights",
    "ar_dc": "Allows an application to read access recommendation insights",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure AD Notification",
    "appDn": "c",
    "appId": "fc03f97a-9db0-4627-a216-ec98ce54e018",
    "p_type": "oa",
    "p_atype": "other",
    "p": "access-as-user",
    "p_id": "0c80a1ae-d4a4-4dfc-acde-ec00fbf86fe8",
    "p_fam": "access-as-user",
    "oa_aCsDn": "AD Notification Teams consent",
    "oa_aCsDc": "AD Notification Teams consent",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure Advanced Threat Protection",
    "appId": "7b7531ad-5926-4f2d-8a1d-38495ad33e17",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Identity.PrivilegeAccountActions",
    "p_id": "c613cf81-75fb-4201-a32b-7a58d1fe4dff",
    "p_fam": "Identity",
    "ar_dn": "get a list of actions and update on the status of said actions",
    "ar_dc": "Allows the app to get a list of actions required on AD and Entra identities and update on the status of said actions for MDI customers.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Analysis Services",
    "appDn": "c",
    "appId": "4ac7d521-0382-477b-b0f8-7e1d95f85ca2",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Model.ReadWrite.All",
    "p_id": "59ef67ea-d35f-4c6d-b1ce-95468f134ccb",
    "p_fam": "Model",
    "oa_aCsDn": "Read and Write all Models",
    "oa_aCsDc": "The app can view and write to all models for the signed in user and models that the user has access to.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "The app can view and write to all of your models and models that you have access to.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure API Center",
    "appDn": "c",
    "appId": "c3ca1a77-7a87-4dba-b8f8-eea115ae4573",
    "p_type": "oa",
    "p_atype": "read",
    "p": "Data.Read.All",
    "p_id": "8351d75c-0972-4fe9-b20b-d91b74614489",
    "p_fam": "Data",
    "oa_aCsDn": "Access Azure API Center Data API",
    "oa_aCsDc": "Allows access to the Azure API Center Data API service on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Azure API for DICOM",
    "appDn": "c",
    "appId": "75e725bf-66ce-4cea-9b9a-5c4caae57f33",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Dicom.ReadWrite",
    "p_id": "e69ab058-b8ae-4c0f-b687-5d97888ddccb",
    "p_fam": "Dicom",
    "oa_aCsDn": "Read and write DICOM",
    "oa_aCsDc": "Allows application to read and write DICOM resources.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure API Hub",
    "appDn": "Azure API Connections",
    "appId": "fe053c5f-3692-4f14-aef2-ee34fc081cae",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Runtime.All",
    "p_id": "6c3012bf-22c1-4bb5-959b-dff738314144",
    "p_fam": "Runtime",
    "oa_aCsDn": "Access Azure API Connections runtime service API",
    "oa_aCsDc": "Have full access to the Azure API Connection service.",
    "oa_uCsDn": "Access Azure API Connections service API.",
    "oa_uCsDc": "Provide data access to the Azure API Connection service.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Azure Cognitive Search",
    "appDn": "c",
    "appId": "880da380-985e-4198-81b9-e05b1cc53158",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "a4165a31-5d9e-4120-bd1e-9d88c66fd3b8",
    "p_fam": None,
    "oa_aCsDn": "user_impersonation ",
    "oa_aCsDc": "Access Azure Cognitive Search",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure Commercial Services Tool - CST",
    "appId": "801546d2-55cc-4ff4-b66d-134b1208deb5",
    "p_type": "ar",
    "p_atype": "read",
    "p": "samples.read",
    "p_id": "801546d2-55cc-4ff4-b66d-134b1208deb5",
    "p_fam": "samples",
    "ar_dn": "CST SP",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure Container Registry",
    "appId": "6a0ec4d3-30cb-4a83-91c0-ae56bc0e3d26",
    "p_type": "ar",
    "p_atype": "other",
    "p": "AzureContainerRegistryRP",
    "p_id": "a25ca244-bc95-4be7-bd58-ca9325bd24b2",
    "p_fam": "AzureContainerRegistryRP",
    "ar_dn": "Azure Container Registry RP",
    "ar_dc": "Azure Container Registry Resource Provider",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure ContainerApps Sessions",
    "appDn": "c",
    "appId": "2c7dd73f-7a21-485b-b97d-a2508fa152c3",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Sessions.ReadWrite.All",
    "p_id": "2843164f-ca31-473a-9198-ceaeb95e59b1",
    "p_fam": "Sessions",
    "oa_aCsDn": "Sessions.ReadWrite.All",
    "oa_aCsDc": "Allows the client application to create and execute sessions that user has access to",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Cosmos DB",
    "appDn": "c",
    "appId": "a232010e-820c-4083-83bb-3ace5fc29d0b",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "8741c20d-e8c0-41ff-8adf-b7b9ba168197",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Cosmos DB",
    "oa_aCsDc": "Allow the application to access Azure Cosmos DB on behalf of the signed-in user.",
    "oa_uCsDn": "Access Azure Cosmos DB as the Signed-in User",
    "oa_uCsDc": "Allow the application to access Azure Cosmos DB on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure CosmosDB for PostgreSQL AAD Authentication",
    "appId": "b4fa09d8-5da5-4352-83d9-05c2a44cf431",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "app_impersonation",
    "p_id": "45b2dd25-66bb-4e03-8945-c0781f29fc85",
    "p_fam": None,
    "ar_dn": "Azure CPG Prod",
    "ar_dc": "Access CPG Prod services from the application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure CosmosDB for PostgreSQL Microsoft EntraId",
    "appId": "ecafc2d9-cf1a-49a7-b60f-e44e34a988d2",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "app_impersonation",
    "p_id": "bb7fb9ee-c8d2-4c3b-853e-af20f589cb42",
    "p_fam": None,
    "ar_dn": "Azure CPG Prod",
    "ar_dc": "Access CPG Prod services from the application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Data Lake",
    "appDn": "c",
    "appId": "e9f49c6b-5ce5-44c8-925d-015017e9f7ad",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "9f15d22d-3cdf-430f-ba48-f75401c0408e",
    "p_fam": None,
    "oa_aCsDn": "Have full access to the Azure Data Lake service",
    "oa_aCsDc": "Allow the application full access to the Azure Data Lake service on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application full access to the Azure Data Lake service on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure Data Manager for Energy",
    "appId": "dffa82c7-cb2f-4a0a-9e8f-7e86fd7b245e",
    "p_type": "ar",
    "p_atype": "other",
    "p": "ADME.ApplicationAccess",
    "p_id": "c0795231-e282-4abc-8822-576cbaea5bfb",
    "p_fam": "ADME",
    "ar_dn": "ADME Application API access",
    "ar_dc": "Allows an application to call ADME apis without a signed in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Device Update",
    "appDn": "c",
    "appId": "6ee392c4-d339-4083-b04d-6b7947c6cf78",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "884024e2-2000-4ca9-aaad-4436358e330c",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Device Update",
    "oa_aCsDc": "Allow the application to access Azure Device Update on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to access Azure Device Update on your behalf.",
    "csReq": "t",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure DevOps",
    "appId": "499b84ac-1321-427f-aa17-267ca6975798",
    "p_type": "ar",
    "p_atype": "other",
    "p": "vso.loadtest",
    "p_id": "e000c422-1bec-45ec-9d30-083f21df9d04",
    "p_fam": "vso",
    "ar_dn": "Load test (read)",
    "ar_dc": "Grants the ability to read your load test runs, test results, and APM artifacts.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Digital Twins",
    "appDn": "c",
    "appId": "0b07f429-9f4b-4714-9392-cc5e8e80c8b0",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Read.Write",
    "p_id": "4589bd03-58cb-4e6c-b17f-b580e39652f8",
    "p_fam": "Read",
    "oa_aCsDn": "Read/Write Access",
    "oa_aCsDc": "Read/Write access for all objects in the space topology",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Digital Twins Authorization PDP",
    "appDn": "c",
    "appId": "c115998b-3d59-49b4-b55b-042a9ba1dbfe",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Read.Write",
    "p_id": "6f0a461a-c02f-4f98-994a-b116efecc7b2",
    "p_fam": "Read",
    "oa_aCsDn": "Read, write Access",
    "oa_aCsDc": "Read, write access for all objects in the space topology",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Enterprise Knowledge Graph RP",
    "appDn": "c",
    "appId": "df8484e9-6636-4a37-a7ad-3ebfe7924fad",
    "p_type": "oa",
    "p_atype": "read",
    "p": "Knowledge.Read",
    "p_id": "df43b147-a9af-4e9b-92f9-c366aa5c2c5c",
    "p_fam": "Knowledge",
    "oa_aCsDn": "Read Microsoft Enterprise Graph data as an organization user (preview)",
    "oa_aCsDc": "Allows the user to access consumption APIs on Microsoft Enterprise Graph",
    "oa_uCsDn": "Read Microsoft Enterprise Graph data (preview)",
    "oa_uCsDc": "Allows the app to read Enterprise Graph data your behalf. ",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure ExP",
    "appId": "e00d2f8a-f6c8-46e4-b379-e66082e28ca8",
    "p_type": "ar",
    "p_atype": "other",
    "p": "az-exp-backend",
    "p_id": "ddae8266-1a14-470c-92bd-5901e981053f",
    "p_fam": "az-exp-backend",
    "ar_dn": "Azure ExP Backend Service",
    "ar_dc": "Role representing Azure ExP backend services.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure HDInsight Cluster API",
    "appId": "7865c1d2-f040-46cc-875f-831a1ef6a28a",
    "p_type": "ar",
    "p_atype": "write",
    "p": "Kafka.ReadWrite",
    "p_id": "bcc42819-54c2-4d19-a7c5-de8402bf34e3",
    "p_fam": "Kafka",
    "ar_dn": "Access Kafka rest proxy apis in HDInsight",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure Healthcare APIs",
    "appId": "4f6778d8-5aef-43dc-a1ff-b073724b9495",
    "p_type": "ar",
    "p_atype": "other",
    "p": "offline_access",
    "p_id": "7f08bce5-b21b-4518-b783-c69c9c0cd658",
    "p_fam": "offline_access",
    "ar_dn": "offline_access",
    "ar_dc": "Grants permission for refresh tokens to be used to obtain a new access token even after the user is no longer online.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Azure Import Export",
    "appId": "7de4d5c5-5b32-4235-b8a9-33b34d6bcd2a",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "26d59185-6d22-461c-98e2-2cd4bcc6911b",
    "p_fam": None,
    "ar_dn": "Azure Import Export",
    "ar_dc": "Azure Import Export service for massive data transferring by shipping disks",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Key Vault",
    "appDn": "c",
    "appId": "cfa8b339-82a2-471a-a3c9-0fc0be7a4093",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "f53da476-18e3-4152-8e01-aec403e6edc0",
    "p_fam": None,
    "oa_aCsDn": "Have full access to the Azure Key Vault service",
    "oa_aCsDc": "Allow the application full access to the Azure Key Vault service on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application full access to the Azure Key Vault service on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Kubernetes Service AAD Server",
    "appDn": "c",
    "appId": "6dae42f8-4368-4678-94ff-3960e28e3630",
    "p_type": "oa",
    "p_atype": "read",
    "p": "user.read",
    "p_id": "34a47c2f-cd0d-47b4-a93c-2c41130c671c",
    "p_fam": "user",
    "oa_aCsDn": "user.read",
    "oa_aCsDc": "this allows to read user profile",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Azure Machine Learning Services",
    "appDn": "c",
    "appId": "18a66f5f-dbdf-4c17-9dd7-1634712a9cbe",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "1a7925b5-f871-417a-9b8b-303f9f29fa10",
    "p_fam": None,
    "oa_aCsDn": "user_impersonation",
    "oa_aCsDc": "Consent for Azure Machine Learning Service",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Maps",
    "appDn": "c",
    "appId": "ba1ea022-5807-41d5-bbeb-292c7e1cf5f6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "1c3162b4-de12-4eb3-b521-088e4e2d6915",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Maps",
    "oa_aCsDc": "Allow the application to access Azure Maps on behalf of the signed-in user.",
    "oa_uCsDn": "Access Azure Maps As the Signed-in User",
    "oa_uCsDc": "Allow the application to access Azure Maps on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Media Services",
    "appDn": "c",
    "appId": "374b2a64-3b6b-436b-934c-b820eacca870",
    "p_type": "oa",
    "p_atype": "other",
    "p": "access_media_service",
    "p_id": "59f34ebf-a919-4365-9cc3-00193275099c",
    "p_fam": "access_media_service",
    "oa_aCsDn": "Access azure media service as signed-in user",
    "oa_aCsDc": "Azure media service API allows creating, modifying, viewing & deleting of media assets",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Access azure media service as signed-in user ",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Azure Monitor Control Service",
    "appDn": "c",
    "appId": "e933bd07-d2ee-4f1d-933c-3752b819567b",
    "p_type": "oa",
    "p_atype": "other",
    "p": "AMA.Ingest",
    "p_id": "8a4fc8e7-d346-4d67-a1d3-e83b55cf3659",
    "p_fam": "AMA",
    "oa_aCsDn": "Read Data Collection Rules",
    "oa_aCsDc": "This scope allows Azure Monitor Agents to access Azure Monitor backends on behalf of the Client Device.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Azure Orbital Planetary Computer",
    "appDn": "Azure Orbital Spatio",
    "appId": "6388acc4-795e-43a9-a320-33075c1eb83b",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "870e9a7e-1d10-42b2-85dc-2cd2b2cd656b",
    "p_fam": None,
    "oa_aCsDn": "Access GeoCatalogs",
    "oa_aCsDc": "Allows the app to access GeoCatalogs on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allows the app to access GeoCatalogs on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure OSSRDBMS Database",
    "appId": "123cd850-d9df-40bd-94d5-c9f07b7fa203",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "app_impersonation",
    "p_id": "017211c5-049f-46b5-a0f0-bcc46299e550",
    "p_fam": None,
    "ar_dn": "OSSRDBMS Azure",
    "ar_dc": "Access OSSRDBMS services from the application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure PKI",
    "appDn": "c",
    "appId": "c4b30b9c-4322-4c9f-9eb7-2167b85bbf5c",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Pki.ReadWrite.All",
    "p_id": "65b05492-d252-4876-b9fb-0a848447f31a",
    "p_fam": "Pki",
    "oa_aCsDn": "Have full read and write access to the PKI service",
    "oa_aCsDc": "Allow the application full read and write access to the PKI service",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "Azure Resource Graph",
    "name": "Azure Resources Topology",
    "appId": "509e4652-da8d-478d-a730-e9d4a1996ca4",
    "p_type": "ar",
    "p_atype": "other",
    "p": "AzureEventGridSecureWebhookSubscriber",
    "p_id": "83262d98-99cb-496d-8da9-e0ceed85d0ed",
    "p_fam": "AzureEventGridSecureWebhookSubscriber",
    "ar_dn": "AzureEventGridSecureWebhookSubscriber",
    "ar_dc": "Azure Event Grid Role",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure Service Deploy",
    "appDn": "c",
    "appId": "5b306cba-9c71-49db-96c3-d17ca2379c4d",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Rollouts.ReadWrite.User",
    "p_id": "bc5c4337-74a0-4a05-864d-576511d9621f",
    "p_fam": "Rollouts",
    "oa_aCsDn": "Azure Service Deploy",
    "oa_aCsDc": "Allows users to deploy Azure resources to one or more regions in a orchestrated manner using an ARM based declarative model.",
    "oa_uCsDn": "Control deployment of resources in the context of the user",
    "oa_uCsDc": "Allows you to deploy Azure resources to one or more regions in an orchestrated manner using ARM-based declarative model.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Azure SQL Database",
    "appId": "022907d3-0f1b-48f7-badc-1ba6abab6d66",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "app_impersonation",
    "p_id": "efe4d732-bfbb-4617-8a77-349a9d67c720",
    "p_fam": None,
    "ar_dn": "Access Azure SQL DB and Data Warehouse",
    "ar_dc": "Access Azure SQL DB and Data Warehouse from the application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Azure SRE Agent",
    "appDn": "c",
    "appId": "59f0a04a-b322-4310-adc9-39ac41e9631e",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Threads.ReadWrite.All",
    "p_id": "c41153e1-cb8a-4a26-ac7e-e6457e0716cf",
    "p_fam": "Threads",
    "oa_aCsDn": "Create conversation threads with SRE agents and reply on existing conversation threads",
    "oa_aCsDc": "Allows the application to create conversation threads and reply on existing threads for the SRE agents that user has access to",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Storage",
    "appDn": "c",
    "appId": "e406a681-f3d4-42a8-90b6-c2b029497af1",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "03e0da56-190b-40ad-a80c-ea378c433f7f",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Storage",
    "oa_aCsDc": "Allow the application to access Azure Storage on behalf of the signed-in user.",
    "oa_uCsDn": "Access Azure Storage As the Signed-in User",
    "oa_uCsDc": "Allow the application to access Azure Storage on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Azure Time Series Insights",
    "appDn": "c",
    "appId": "120d688d-1518-4cf7-bd38-182f158850b6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "a3a77dfe-67a4-4373-b02a-dfe8485e2248",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Time Series Insights service",
    "oa_aCsDc": "Allow the application full access to the Azure Time Series Insights service on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "AzureCommunicationsGateway",
    "appId": "8502a0ec-c76d-412f-836c-398018e2312b",
    "p_type": "ar",
    "p_atype": "other",
    "p": "ProvisioningAPI.Admin",
    "p_id": "de5aee63-7b89-495b-879a-0c5d6462594d",
    "p_fam": "ProvisioningAPI",
    "ar_dn": "ProvisioningAPI.Admin",
    "ar_dc": "Allows an application to invoke any operation across the provisioning API.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "AzureDatabricks",
    "appDn": "c",
    "appId": "2ff814a6-3304-4ab8-85cb-cd0e6f879c1d",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "739272be-e143-11e8-9f32-f2801f1b9fd1",
    "p_fam": None,
    "oa_aCsDn": "user_impersonation",
    "oa_aCsDc": "allows the user to have full access to Azure Databricks",
    "oa_uCsDn": "Have full access to Azure Databricks",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "AzureQuantum",
    "appDn": "c",
    "appId": "a77d91dc-971b-4cf7-90c8-f183194249bc",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Jobs.ReadWrite",
    "p_id": "52109446-c0d3-4e4f-9e8a-35bbee6b8b7d",
    "p_fam": "Jobs",
    "oa_aCsDn": "Jobs.ReadWrite",
    "oa_aCsDc": "Allow the app to submit and retrieve jobs.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "Billing RP",
    "name": "Billing",
    "appId": "80dbdb39-4f33-4799-8b6f-711b5e3e61b6",
    "p_type": "ar",
    "p_atype": "other",
    "p": "AddressCustomerMasterReader",
    "p_id": "1cbc9fa5-af3f-44ad-9455-35ef4dd212aa",
    "p_fam": "AddressCustomerMasterReader",
    "ar_dn": "AddressCustomerMasterReader",
    "ar_dc": "Address Customer Master Reader",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Bing",
    "appId": "9ea1ad79-fdb6-4f9a-8bc3-2b70f96e34c7",
    "p_type": "ar",
    "p_atype": "other",
    "p": "bawuser",
    "p_id": "cfc0dc64-9211-4513-9d32-c387680182cf",
    "p_fam": "bawuser",
    "ar_dn": "Preview User",
    "ar_dc": "Allows members of a special preview group to use experimental features of Bing",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Bot Framework Dev Portal",
    "appId": "f3723d34-6ff5-4ceb-a148-d99dcd2511fc",
    "p_type": "ar",
    "p_atype": "other",
    "p": "BingReviewer",
    "p_id": "c9774c15-ca59-44c2-8934-14892b976eeb",
    "p_fam": "BingReviewer",
    "ar_dn": "Bing Bot Reviewer",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Branch Connect Web Service",
    "appId": "57084ef3-d413-4087-a28f-f6f3b1ad7786",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Bcos.ReadOnly",
    "p_id": "c6a7f3e3-dea5-4df4-a094-59ceca797083",
    "p_fam": "Bcos",
    "ar_dn": "Bcos.ReadOnly",
    "ar_dc": "Read-only access to Bcos resources",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "CABProvisioning",
    "appId": "5da7367f-09c8-493e-8fd4-638089cddec3",
    "p_type": "ar",
    "p_atype": "other",
    "p": "user.invite.all",
    "p_id": "7431916a-fe67-40b3-b273-602ffe516093",
    "p_fam": "user",
    "ar_dn": "Invite users to tenant",
    "ar_dc": "Allows application to invite users to tenant",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "CompositeSolutions-Canary",
    "appDn": "c",
    "appId": "b25aed92-5d07-4c42-9417-e5cf7470a1c4",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Deployment.ReadWrite",
    "p_id": "35bae7a0-c6c0-4835-b671-89f0f1736121",
    "p_fam": "Deployment",
    "oa_aCsDn": "Read and write composite solutions",
    "oa_aCsDc": "Allows the app to read and deploy composite solutions, on your behalf",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Compute Recommendation Service",
    "appId": "b9a92e36-2cf8-4f4e-bcb3-9d99e00e14ab",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Crs.Api.All",
    "p_id": "f155dcbc-e393-438b-b343-92699349582d",
    "p_fam": "Crs",
    "ar_dn": "Call all CRS APIs",
    "ar_dc": "This allows applications to call CRS APIs.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Configuration Manager Microservice",
    "appId": "557c67cf-c916-4293-8373-d584996f60ae",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Account.Read.All",
    "p_id": "c8750fbf-30e2-40ed-8519-e2876cbeccb9",
    "p_fam": "Account",
    "ar_dn": "Read account onboarding data",
    "ar_dc": "Allows to call service API to query account onboarding data",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "ConnectionsService",
    "appDn": "c",
    "appId": "b7912db9-aa33-4820-9d4f-709830fdd78f",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "04d2d44f-432b-4f9b-be28-cb651a028099",
    "p_fam": None,
    "oa_aCsDn": "Access Connections Service Api",
    "oa_aCsDc": "Access Connections Service Api",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Connectors",
    "appDn": "c",
    "appId": "48af08dc-f6d2-435f-b2a7-069abd99c086",
    "p_type": "oa",
    "p_atype": "write",
    "p": "webhook.readwrite.all",
    "p_id": "ba9c6a98-63fd-487c-b835-c1f895764e25",
    "p_fam": "webhook",
    "oa_aCsDn": "Read and write connector configurations",
    "oa_aCsDc": "Allows the app to create and manage connector configurations. The app would use the connector configuration to send actionable messages to your inbox or a group of your choice.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Consumption Billing",
    "appId": "12ff570a-8284-47ed-adb3-fcc72b594c36",
    "p_type": "ar",
    "p_atype": "read",
    "p": "CBS.Reporting.Read",
    "p_id": "866040a7-8984-4760-8e56-363aefb78d69",
    "p_fam": "CBS",
    "ar_dn": "GET Consumption Bill Report for a tenant",
    "ar_dc": "Authorized to call the Consumption Billing reporting API for a single tenant id",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Cortana at Work Bing Services",
    "appId": "22d7579f-06c2-4baa-89d2-e844486adb9d",
    "p_type": "ar",
    "p_atype": "write",
    "p": "BingCortana-Internal.ReadWrite",
    "p_id": "f78726f6-cf77-45f6-ae8b-87d4b8bd7a2c",
    "p_fam": "BingCortana-Internal",
    "ar_dn": "BingCortana-Internal.ReadWrite",
    "ar_dc": "Permissions for an internal Cortana application to read and write all Cortana user data",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Cortana at Work Service",
    "appId": "2a486b53-dbd2-49c0-a2bc-278bdfc30833",
    "p_type": "ar",
    "p_atype": "write",
    "p": "BingCortana-Internal.ReadWrite",
    "p_id": "ab725b17-4fd4-46ee-a0bf-102895a209e3",
    "p_fam": "BingCortana-Internal",
    "ar_dn": "BingCortana-Internal.ReadWrite",
    "ar_dc": "Permissions for an internal Cortana application to read and write all Cortana user data",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Cortana Runtime Service",
    "appId": "81473081-50b9-469a-b9d8-303109583ecb",
    "p_type": "ar",
    "p_atype": "write",
    "p": "BingCortana-Internal.ReadWrite",
    "p_id": "c9265686-1717-4d25-a640-1f46263a162c",
    "p_fam": "BingCortana-Internal",
    "ar_dn": "BingCortana-Internal.ReadWrite",
    "ar_dc": "Permission for internal Cortana applications",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Data Migration Service",
    "appDn": "c",
    "appId": "a4bad4aa-bf02-4631-9f78-a64ffdba8150",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "97d27738-4e13-4a25-b26d-d150c4502d0f",
    "p_fam": None,
    "oa_aCsDn": "Access Data Migration Service",
    "oa_aCsDc": "Allow the application to access Data Migration Service on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to access Data Migration Service on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "DeploymentScheduler",
    "appId": "8bbf8725-b3ca-4468-a217-7c8da873186e",
    "p_type": "ar",
    "p_atype": "read",
    "p": "deploymenttask.read",
    "p_id": "a0f3e90e-0c99-4c7d-bfaf-69531a09579c",
    "p_fam": "deploymenttask",
    "ar_dn": "DeploymentTask.Read",
    "ar_dc": "allows access to read DeploymentTask and UpdatePolicy",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Device Registration Service",
    "appDn": "c",
    "appId": "01cb2876-7ebd-4aa4-9cc9-d28bd4d359a9",
    "p_type": "oa",
    "p_atype": "other",
    "p": "self_service_device_delete",
    "p_id": "086327cd-9afe-4777-8341-b136a1866bb3",
    "p_fam": "self_service_device_delete",
    "oa_aCsDn": "User can delete devices that belong to them",
    "oa_aCsDc": "Allow the application permissions to delete any device registered to the signed-in user",
    "oa_uCsDn": "Delete devices that belong to me",
    "oa_uCsDc": "Allow the application to delete your devices on your behalf",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Diagnostic Services Data Access",
    "appDn": "c",
    "appId": "3603eff4-9141-41d5-ba8f-02fb3a439cd6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "384a9d29-7ed2-4fc4-b781-1aa48cb2b883",
    "p_fam": None,
    "oa_aCsDn": "Access Diagnostic Services",
    "oa_aCsDc": "Allow the application to access Diagnostic Services on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to access Diagnostic Services on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "DirectoryLookupService",
    "appId": "9cd0f7df-8b1a-4e54-8c0c-0ef3a51116f6",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Users.Read.All",
    "p_id": "b0dc367b-7342-44c8-9816-d5f9ade99d5d",
    "p_fam": "Users",
    "ar_dn": "Users.Read.All",
    "ar_dc": "This allows app to access prod user profile",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Discovery data-plane service App",
    "appDn": "c",
    "appId": "bc51a560-ae79-4282-99f5-9346aecfc860",
    "p_type": "oa",
    "p_atype": "other",
    "p": "access_as_user",
    "p_id": "89262da0-2b68-4c38-a6eb-79d067511de8",
    "p_fam": "access_as_user",
    "oa_aCsDn": "Access Microsoft.Discovery service as a user",
    "oa_aCsDc": "Allows the application to access the Microsoft.Discovery data-plane services as a user in the organization",
    "oa_uCsDn": "Access Microsoft.Discovery as you",
    "oa_uCsDc": "Allows the application to access Microsoft.Discovery as you.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "DNC",
    "appId": "1efe5bbf-d5b1-4fe9-99fa-f55ce1c88679",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Dnc.Application.All",
    "p_id": "d220ea05-1e7a-47bd-a414-7215922c7cab",
    "p_fam": "Dnc",
    "ar_dn": "Dnc.Application.All",
    "ar_dc": "access dnc as application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Domain Controller Services",
    "appId": "2565bd9d-da50-47d4-8b85-4c97f669dc36",
    "p_type": "ar",
    "p_atype": "other",
    "p": None,
    "p_id": "93619254-dea7-4abb-8354-01ae2d9b781d",
    "p_fam": None,
    "ar_dn": "msiam_access",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "DTS-Authentication",
    "appDn": "Durable Task Scheduler",
    "appId": "887c6b43-ba92-4adb-a82b-73670fc48dac",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Execute",
    "p_id": "2fd36249-0769-40b9-bf88-00cb556e2594",
    "p_fam": "Execute",
    "oa_aCsDn": "Execute",
    "oa_aCsDc": "Get orchestration and activity work-items, and post results",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "DWEngineV2",
    "appDn": "c",
    "appId": "441509e5-a165-4363-8ee7-bcf0b7d26739",
    "p_type": "oa",
    "p_atype": "write",
    "p": "TopicSuggestion-Internal.ReadWrite",
    "p_id": "e6d57537-d278-4cb8-9f1d-19e173bcf4eb",
    "p_fam": "TopicSuggestion-Internal",
    "oa_aCsDn": "TopicSuggestion-Internal.ReadWrite",
    "oa_aCsDc": "Allow clients to read topic suggestions and update their status",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the app to read topic suggestions and update their status",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Dynamics 365 Business Central",
    "appId": "996def3d-b36c-4153-8607-a6fd3c01b89f",
    "p_type": "ar",
    "p_atype": "write",
    "p": "AdminCenter.ReadWrite.All",
    "p_id": "a20fe46f-4f63-4666-8e0e-9b882d90b837",
    "p_fam": "AdminCenter",
    "ar_dn": "Full access to Admin Center API",
    "ar_dc": "Grants full access to the Business Central Admin Center API. This API provides capability to execute administrative tasks for a Business Central tenant.",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "EASM API",
    "appDn": "c",
    "appId": "b7faa489-a4c8-4b39-bb0c-842c3de2de6a",
    "p_type": "oa",
    "p_atype": "read",
    "p": "AssetResource.Read.All",
    "p_id": "2288f070-b471-48c3-b16b-113c05a3cfbb",
    "p_fam": "AssetResource",
    "oa_aCsDn": "Read Asset Resource information",
    "oa_aCsDc": "Allows the user to read Asset Resource, including asset resource, asset audit trails, asset summary and asset snapshot, on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allows the user to read Asset Resource information, including asset resource, asset audit trails, asset summary and asset snapshot, on your behalf.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Edge Zone RP API - Prod",
    "appId": "a92d1ca6-25ad-4531-a09f-3648ed976dbf",
    "p_type": "ar",
    "p_atype": "other",
    "p": "EdgeZoneRpApi.Contributor",
    "p_id": "453ddc3f-d897-4299-9ca1-6401b3313412",
    "p_fam": "EdgeZoneRpApi",
    "ar_dn": "EdgeZoneRpApi.Contributor",
    "ar_dc": "Contributors have the ability to make all requests supported by the API, for any subscription",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "EventGrid Data API",
    "appDn": "c",
    "appId": "823c0a78-5de0-4445-a7f5-c2f42d7dc89b",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "d5f985b8-5529-49be-926a-58f4a026c488",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Event Grid",
    "oa_aCsDc": "Allow the application to access Azure Event Grid on behalf of the signed-in user.",
    "oa_uCsDn": "Access Azure Event Grid As the Signed-in User",
    "oa_uCsDc": "Allow the application to access Azure Event Grid on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Fidalgo Dataplane Public",
    "appId": "e526e72f-ffae-44a0-8dac-cf14b8bd40e2",
    "p_type": "ar",
    "p_atype": "create",
    "p": "actonbehalfof.create.all",
    "p_id": "b1a7c8e2-1234-4cde-9876-abcdef123456",
    "p_fam": "actonbehalfof",
    "ar_dn": "Act On Behalf Of - Create All",
    "ar_dc": "Allows the app to create resources on behalf of eligible users when policy and RBAC permit.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Fiji Storage",
    "appDn": "Azure Edge Zones storage",
    "appId": "1609d3a1-0db2-4818-b854-fe1614f0718a",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "4e5661b3-5a0d-47fc-b7a6-e5b659cfea8b",
    "p_fam": None,
    "oa_aCsDn": "Access Fiji Storage",
    "oa_aCsDc": "Allow the application to access Fiji Storage on behalf of the signed-in user.",
    "oa_uCsDn": "Access Fiji Storage As the Signed-in User",
    "oa_uCsDc": "Allow the application to access Fiji Storage on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Graph Connector Service",
    "appId": "56c1da01-2129-48f7-9355-af6d59d42766",
    "p_type": "ar",
    "p_atype": "read",
    "p": "ExternalConnection.Read.All",
    "p_id": "1ef94f6e-ade0-4b79-9f7f-a72563e3ad60",
    "p_fam": "ExternalConnection",
    "ar_dn": "ExternalConnection.Read.All",
    "ar_dc": "Allows the app to read all external connections without a signed-in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Health Bot Portal V4",
    "appDn": "c",
    "appId": "5771b6e6-1c79-4c0f-940f-9d6412d465de",
    "p_type": "oa",
    "p_atype": "other",
    "p": "AzureHealthBot.PortalAccess",
    "p_id": "4d148aae-170b-417a-9d06-6978383e329a",
    "p_fam": "AzureHealthBot",
    "oa_aCsDn": "AzureHealthBot.PortalAccess",
    "oa_aCsDc": "Access the Azure Health Bot",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Health Safeguards REST API",
    "appDn": "Healthcare Agent Service APIs",
    "appId": "1489b232-2872-41d9-aea6-2c549132f732",
    "p_type": "oa",
    "p_atype": "other",
    "p": "HealthcareAgentServiceApis.Process",
    "p_id": "28e41776-5350-4c1e-9ee4-689de5cb6d85",
    "p_fam": "HealthcareAgentServiceApis",
    "oa_aCsDn": "Healthcare Agent Service APIs Process",
    "oa_aCsDc": "Allow Healthcare Agent Service APIs to process the data sent to it.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "IAM Supportability",
    "appDn": "c",
    "appId": "a57aca87-cbc0-4f3c-8b9e-dc095fdc8978",
    "p_type": "oa",
    "p_atype": "other",
    "p": "invoke",
    "p_id": "8040cfef-0635-4aa6-b099-9f40d6866bbb",
    "p_fam": "invoke",
    "oa_aCsDn": "Invoke Diagnostics",
    "oa_aCsDc": "Invoke Diagnostics",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Intelligent Recommendations Service",
    "appDn": "c",
    "appId": "c5b731db-1b0a-43f6-bcf6-757667d9cdc6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "47e2b85b-5704-487f-be47-74aa52bbe838",
    "p_fam": None,
    "oa_aCsDn": "Dynamics 365 Recommendations",
    "oa_aCsDc": "Allow the application to access Dynamics 365 Recommendations on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to access Dynamics 365 Recommendations on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "KustoService",
    "appDn": "Azure Data Explorer",
    "appId": "2746ea77-4702-4b45-80ca-3c97e680e8b7",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "00d678f0-da44-4b12-a6d6-c98bcfd1c5fe",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Data Explorer",
    "oa_aCsDc": "Allow the application to access Azure Data Explorer on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to access Azure Data Explorer on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Log Analytics API",
    "appId": "ca7f3f0b-7d91-482c-8e09-c5d840d0eac5",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Data.Read",
    "p_id": "e8f6e161-84d0-4cd7-9441-2d46ec9ec3d5",
    "p_fam": "Data",
    "ar_dn": "Read Log Analytics data",
    "ar_dc": "Allow this application to access Log Analytics data on",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "M365 Pillar Diagnostics Service",
    "appDn": "c",
    "appId": "58ea322b-940c-4d98-affb-345ec4cccb92",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Diagnostic.Execute.All",
    "p_id": "2417f470-7490-419f-820a-144a3ba39e79",
    "p_fam": "Diagnostic",
    "oa_aCsDn": "Diagnostic.Execute.All",
    "oa_aCsDc": "Grants access to execute diagnostics",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "M365DataAtRestEncryption",
    "appId": "c066d759-24ae-40e7-a56f-027002b5d3e4",
    "p_type": "ar",
    "p_atype": "write",
    "p": "CustomerKeyOnboarding-Internal.ReadWrite.All",
    "p_id": "837e1541-7f8b-4fcf-a215-12fe252cd3e2",
    "p_fam": "CustomerKeyOnboarding-Internal",
    "ar_dn": "CustomerKeyOnboarding-Internal.ReadWrite.All",
    "ar_dc": "This scope allows the holder to invoke customer onboarding scenarios",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "MDATPNetworkScanAgent",
    "appId": "04687a56-4fc2-4e36-b274-b862fb649733",
    "p_type": "ar",
    "p_atype": "other",
    "p": "NetworkScanAgent.Operate",
    "p_id": "2adb0da9-d999-4186-85a4-0b66bbd9a535",
    "p_fam": "NetworkScanAgent",
    "ar_dn": "NetworkScanAgent.Operate",
    "ar_dc": "Used to get token for agent to get network scan tasks",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "Security Copilot API",
    "name": "Medeina Service",
    "appId": "bb3d68c2-d09e-4455-94a0-e323996dbaa3",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Medeina.App",
    "p_id": "85e2c024-8528-488c-a14e-42b99dfb2635",
    "p_fam": "Medeina",
    "ar_dn": "Medeina.App",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Medeina Service Dev",
    "appDn": "Security Copilot",
    "appId": "826870f9-9fbb-4f23-81b8-3a957080dfa2",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Medeina.Access",
    "p_id": "fa228bfa-2a9b-48e9-9145-9ac39ac9b6f8",
    "p_fam": "Medeina",
    "oa_aCsDn": "Mediena.Access",
    "oa_aCsDc": "Allows users to access the Medeina APIs",
    "oa_uCsDn": "Medeina.Access",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Microsoft Azure App Service",
    "appDn": "c",
    "appId": "abfa0a7c-a6b6-4736-8310-5855508787cd",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "e0ea806b-d128-49dc-ac08-2bf18f7874d8",
    "p_fam": None,
    "oa_aCsDn": "Access APIs registered with App Service",
    "oa_aCsDc": "Allow the application to access all the APIs registered with App Service",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft Azure Batch",
    "appDn": "c",
    "appId": "ddbf3205-c6bd-46ae-8127-60eb93363864",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "635ced16-958c-4230-8508-ac2c509d94c6",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Batch Service",
    "oa_aCsDc": "Allow the application to access the Azure Batch Service API on behalf of the signed-in user.",
    "oa_uCsDn": "Full access to Azure Batch Service API",
    "oa_uCsDc": "Allow the application to access all Azure Batch Service functionality on your behalf.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft Azure Signup Portal",
    "appDn": "c",
    "appId": "8e0e8db5-b713-4e91-98e6-470fed0aa4c2",
    "p_type": "oa",
    "p_atype": "other",
    "p": "azuregrowth.api.signup",
    "p_id": "df5e5f31-cc73-4a31-9291-89348976337e",
    "p_fam": "azuregrowth",
    "oa_aCsDn": "Azure Growth Signup",
    "oa_aCsDc": "Allows the application to access Azure Growth Signup APIs acting as signed-in users",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allows the application to access Signup APIs acting as signed-in users",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Azure Stack HCI Service",
    "appId": "1322e676-dee7-41ee-a874-ac923822781c",
    "p_type": "ar",
    "p_atype": "other",
    "p": "AzureStackHCI.Billing.Sync",
    "p_id": "7c2ddece-a157-4a29-a61a-1f8116e7cc57",
    "p_fam": "AzureStackHCI",
    "ar_dn": "Sync billing information",
    "ar_dc": "Allows synchronizing billing information, such as the number of physical processor cores, between the Azure Stack HCI cluster and the cloud.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Azure Stream Analytics",
    "appDn": "c",
    "appId": "66f1e791-7bfb-4e18-aed8-1720056421c7",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "27fa5b85-cf15-41f1-a29d-2e44dde75208",
    "p_fam": None,
    "oa_aCsDn": "Stream Analytics access to Power BI",
    "oa_aCsDc": "Stream Analytics access to Power BI",
    "oa_uCsDn": "Allow Stream Analytics to access to Power BI on your behalf",
    "oa_uCsDc": "Allow Stream Analytics to access to Power BI on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft Azure Synapse Gateway",
    "appDn": "c",
    "appId": "1ac05c7e-12d2-4605-bf9d-549d7041c6b3",
    "p_type": "oa",
    "p_atype": "other",
    "p": "workspaceartifacts.management",
    "p_id": "f99087ab-db8f-46be-8ff0-613ef11c6ed8",
    "p_fam": "workspaceartifacts",
    "oa_aCsDn": "workspaceartifacts.management",
    "oa_aCsDc": "This scope allows working with Microsoft Project Arcadia Workspaces' Artifacts API.",
    "oa_uCsDn": "Manage Workspace Artifacts",
    "oa_uCsDc": "Allow the client to work with Microsoft Project Arcadia Workspaces' Artifacts API.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Cloud App Security",
    "appId": "05a65629-4c1b-48c1-a78b-804c4abdd4af",
    "p_type": "ar",
    "p_atype": "manage",
    "p": "discovery.manage",
    "p_id": "f6e78c1a-b9c7-42d3-b067-220689a7a2e9",
    "p_fam": "discovery",
    "ar_dn": "discovery.manage",
    "ar_dc": "Manage discovery alerts, reports, apps, and other related information",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Cognitive Services",
    "appDn": "c",
    "appId": "7d312290-28c8-473c-a0ed-8e53749b6d6d",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "5f1e8914-a52b-429f-9324-91b92b81adaf",
    "p_fam": None,
    "oa_aCsDn": "Access Cognitive Services API as organization users.",
    "oa_aCsDc": "Allows the application to access the Cognitive Services API acting as users in the organization.",
    "oa_uCsDn": "Access Cognitive Services on behalf of you.",
    "oa_uCsDc": "Allows the application to access Cognitive Services on behalf of you.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "Dynamics 365 AI for Customer Insights - NON-PROD",
    "name": "Microsoft Customer Insights",
    "appId": "38c77d00-5fcb-4cce-9d93-af4738258e3c",
    "p_type": "ar",
    "p_atype": "other",
    "p": "CustomerInsights.Api.All",
    "p_id": "056209dc-5c35-434b-9569-0c77d4aa6047",
    "p_fam": "CustomerInsights",
    "ar_dn": "Have third-party access to Microsoft Customer Insights Service API",
    "ar_dc": "Allow third-party application access to the Microsoft Customer Insights Service API.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Device Directory Service",
    "appDn": "c",
    "appId": "8f41dc7c-542c-4bdd-8eb3-e60543f607ca",
    "p_type": "oa",
    "p_atype": "read",
    "p": "dds.read",
    "p_id": "79a8f059-5727-4e7d-986a-d509f1799603",
    "p_fam": "dds",
    "oa_aCsDn": "See your list of devices",
    "oa_aCsDc": "Allows the app to see your list of devices as well as devices shared in your family.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Exchange Online Protection",
    "appId": "00000007-0000-0ff1-ce00-000000000000",
    "p_type": "ar",
    "p_atype": "other",
    "p": "EopPolicySync.AccessAsApp",
    "p_id": "c79b0778-99a8-4d45-9063-3f160ec2776d",
    "p_fam": "EopPolicySync",
    "ar_dn": "EopPolicySync.AccessAsApp",
    "ar_dc": "Scope to allow FirstParty APPS to make PolicySync calls",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Graph",
    "appId": "00000003-0000-0000-c000-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "AccessReview.Read.All",
    "p_id": "d07a8cc0-3d51-4b77-b3b0-32704d1f69fa",
    "p_fam": "AccessReview",
    "ar_dn": "Read all access reviews",
    "ar_dc": "Allows the app to read access reviews, reviewers, decisions and settings in the organization, without a signed-in user.",
    "csReq": "t",
    "crt": "see EntraOps classification",
    "APIAM_Ct": "Entitlement Management",
    "APIAM_EAMTL": "ManagementPlane"
  },
  {
    "appDn": "c",
    "name": "Microsoft Graph Connectors Core",
    "appId": "f8f7a2aa-e116-4ba6-8aea-ca162cfa310d",
    "p_type": "ar",
    "p_atype": "read",
    "p": "ContentDomain.Read.All",
    "p_id": "bbee328f-fe32-4251-a58c-9b16f9bf50c8",
    "p_fam": "ContentDomain",
    "ar_dn": "ContentDomain.Read.All",
    "ar_dc": "Allows the current signed-in user to read Content Domain information.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Information Protection API",
    "appId": "40775b29-2688-46b6-a3b5-b256bd04df9f",
    "p_type": "ar",
    "p_atype": "read",
    "p": "InformationProtectionPolicy.Read.All",
    "p_id": "dfa45ec9-c9fd-4944-93c8-d07af06cfa40",
    "p_fam": "InformationProtectionPolicy",
    "ar_dn": "InformationProtectionPolicy.Read.All",
    "ar_dc": "Read all published labels and label policies for an organization.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Information Protection Sync Service",
    "appId": "870c4f2e-85b6-4d43-bdda-6ed9a579b725",
    "p_type": "ar",
    "p_atype": "read",
    "p": "UnifiedPolicy.Tenant.Read",
    "p_id": "8b2071cd-015a-4025-8052-1c0dba2d3f64",
    "p_fam": "UnifiedPolicy",
    "ar_dn": "Read all unified policies of the tenant.",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Intune",
    "appDn": "c",
    "appId": "0000000a-0000-0000-c000-000000000000",
    "p_type": "oa",
    "p_atype": "other",
    "p": "MicrosoftTunnelGatewayEnrollment",
    "p_id": "e323f13a-1fcc-49cc-883f-c6da13ae0542",
    "p_fam": "MicrosoftTunnelGatewayEnrollment",
    "oa_aCsDn": "MicrosoftTunnelGatewayEnrollment",
    "oa_aCsDc": "Allows Intune Admins to enroll a Microsoft Tunnel Gateway Agent",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Microsoft Intune AAD BitLocker Recovery Key Integration",
    "appDn": "c",
    "appId": "ccf4d8df-75ce-4107-8ea5-7afd618d4d8a",
    "p_type": "oa",
    "p_atype": "read",
    "p": "IntuneAADBitLockerRecoveryKey.Read",
    "p_id": "ecff1a9d-e6bb-4e01-9136-c8825bbfceb3",
    "p_fam": "IntuneAADBitLockerRecoveryKey",
    "oa_aCsDn": "Read BitLocker recovery keys",
    "oa_aCsDc": "Allows user to view their BitLocker recovery keys",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow app to read your BitLocker recovery keys",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Intune API",
    "appId": "c161e42e-d4df-4a3d-9b42-e7a3c31f59d4",
    "p_type": "ar",
    "p_atype": "other",
    "p": "get_data_warehouse",
    "p_id": "3d9dc976-32fb-45a8-90bd-c9f8a850d098",
    "p_fam": "get_data_warehouse",
    "ar_dn": "Get data warehouse information from Microsoft Intune",
    "ar_dc": "Grants access to the Intune data warehouse API",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Intune Enrollment",
    "appDn": "c",
    "appId": "d4ebce55-015a-49b5-a083-c84d1797ae8c",
    "p_type": "oa",
    "p_atype": "write",
    "p": "AppleDeviceInfo.ReadWrite",
    "p_id": "830bc8bc-f872-4624-8386-0013e444366d",
    "p_fam": "AppleDeviceInfo",
    "oa_aCsDn": "AppleDeviceInfo.ReadWrite",
    "oa_aCsDc": "Allow users to report info on their Apple Device.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft Intune IW Service",
    "appDn": "c",
    "appId": "b8066b99-6e67-41be-abfa-75db1a2c8809",
    "p_type": "oa",
    "p_atype": "other",
    "p": "branding.search",
    "p_id": "17c38fce-d62f-4e61-85d1-d60852e316a2",
    "p_fam": "branding",
    "oa_aCsDn": "branding.search",
    "oa_aCsDc": "Allows users to search for their custom branding information.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Invoicing",
    "appId": "b6b84568-6c01-4981-a80f-09da9a20bbed",
    "p_type": "ar",
    "p_atype": "other",
    "p": "app_access",
    "p_id": "d3010f21-1088-4717-b6b6-60f186f268f6",
    "p_fam": "app_access",
    "ar_dn": "Access according to the application's permissions in Microsoft Invoicing",
    "ar_dc": "Microsoft Invoicing for Office 365",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft IoT Central",
    "appDn": "c",
    "appId": "9edfcdd9-0bc5-4bd4-b287-c3afc716aac7",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Application.ReadWrite.All",
    "p_id": "51f99752-487f-4501-af40-90beb78bdaa2",
    "p_fam": "Application",
    "oa_aCsDn": "Application Readwrite",
    "oa_aCsDc": "create app",
    "oa_uCsDn": "Ludruda",
    "oa_uCsDc": "ludruda",
    "csReq": "t",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Microsoft Mixed Reality",
    "appId": "c7ddd9b4-5172-4e28-bd29-1e0792947d18",
    "p_type": "ar",
    "p_atype": "other",
    "p": "arrtest.signin",
    "p_id": "49b8cb69-fa3b-4f0c-a198-62506e47dba1",
    "p_fam": "arrtest",
    "ar_dn": "arrtest.signin",
    "ar_dc": "Sign in to Remote Rendering service",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Mobile Application Management",
    "appDn": "c",
    "appId": "0a5f63c0-b750-4f38-a71c-4fc0d58b89e2",
    "p_type": "oa",
    "p_atype": "write",
    "p": "DeviceManagementManagedApps.ReadWrite",
    "p_id": "3c7192af-9629-4473-9276-d35e4e4b36c5",
    "p_fam": "DeviceManagementManagedApps",
    "oa_aCsDn": "Read and Write the User's App Management data",
    "oa_aCsDc": "Allows the Application to read and write the user's data pertaining to itself in the Intune Mobile Application Management service",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allows the Application to read and write data pertaining to itself in the Intune Mobile Application Management service",
    "csReq": "t",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Microsoft password reset service",
    "appId": "93625bc8-bfe2-437a-97e0-3d0060024faa",
    "p_type": "ar",
    "p_atype": "other",
    "p": "PasswordWriteback.OffboardClient.All",
    "p_id": "69201c67-737b-4a20-8f16-e0c8c64e0b0e",
    "p_fam": "PasswordWriteback",
    "ar_dn": "Read, write and manage Microsoft Entra Connect Sync Agent",
    "ar_dc": "Allows the app to uninstall Microsoft Entra Connect Sync Agent and offboard SSPR for the tenant",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft People Cards Service",
    "appDn": "c",
    "appId": "394866fc-eedb-4f01-8536-3ff84b16be2a",
    "p_type": "oa",
    "p_atype": "read",
    "p": "Calendar.Read",
    "p_id": "de374d49-137d-465b-b4bb-ef2cec26583f",
    "p_fam": "Calendar",
    "oa_aCsDn": "Access the Office People API",
    "oa_aCsDc": "Allow access the Office People API",
    "oa_uCsDn": "Access to Office People API",
    "oa_uCsDc": "Allow access to Office People API",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Power Platform Service - PROD",
    "appId": "e64bd61e-5424-451f-b666-e02ee2878437",
    "p_type": "ar",
    "p_atype": "read",
    "p": "VNET.Read.All",
    "p_id": "e2159836-d709-4343-a518-8bb0e5744afa",
    "p_fam": "VNET",
    "ar_dn": "VNET.Read.All",
    "ar_dc": "Allows data plane access to all VNETs on the system",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Premonition",
    "appId": "29cbdf6b-6a1b-44cd-ac51-e18d8a591238",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Library.Read",
    "p_id": "91fb9a45-6b1c-4d38-b915-4f1987a64c1c",
    "p_fam": "Library",
    "ar_dn": "Visitor",
    "ar_dc": "Allows reading library resources",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "Azure Purview",
    "name": "Microsoft Project Babylon",
    "appId": "73c2949e-da2d-457a-9607-fcc665198967",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Purview.ApplicationAccess",
    "p_id": "8d48872e-7710-4001-bfd0-7dac15c28f69",
    "p_fam": "Purview",
    "ar_dn": "Purview Application API Access",
    "ar_dc": "Allows the application to call Purview APIs without a signed-in user",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Remote Desktop",
    "appDn": "c",
    "appId": "a4a365df-50f1-4397-bc59-1a1564b8bb9c",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "dc5f2fe2-469e-48e9-87e5-6e48938b8789",
    "p_fam": None,
    "oa_aCsDn": "Sign in to Windows",
    "oa_aCsDc": "Allow the application to sign in to Windows on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to sign in to Windows on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Microsoft Rights Management Services",
    "appId": "00000012-0000-0000-c000-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Application.Read.All",
    "p_id": "e23bd57d-bfd5-4906-867f-89fb5ed8cd43",
    "p_fam": "Application",
    "ar_dn": "Read all service configuration and log data for the Azure Information Protection service.",
    "ar_dc": "Allows the application to get or read all service configuration and log data",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Sentinel Situational Awareness Workspace Access",
    "appDn": "c",
    "appId": "949eebbd-6fe4-4eb5-a25e-a9bf12d6b96e",
    "p_type": "oa",
    "p_atype": "other",
    "p": "UserImpersonation",
    "p_id": "be810c4b-8598-4528-a3e3-1736473d6bf8",
    "p_fam": "UserImpersonation",
    "oa_aCsDn": "Situational Awareness User Impersonation",
    "oa_aCsDc": "Allow the app to access Log Analytics on behalf of the signed-in user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the app to access Log Analytics on your behalf",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Service Trust",
    "appId": "d6fdaa33-e821-4211-83d0-cf74736489e1",
    "p_type": "ar",
    "p_atype": "write",
    "p": "CustomerManagement.ReadWrite.CPMC",
    "p_id": "6dc96d9f-75cd-4c03-a450-6bf81a89ad9e",
    "p_fam": "CustomerManagement",
    "ar_dn": "CustomerManagement.ReadWrite.CPMC",
    "ar_dc": "Allows applications to read and write CPMC vocabularies for various tenants",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft Threat Protection",
    "appId": "8ee8fdad-f234-4243-8f3b-15c294843740",
    "p_type": "ar",
    "p_atype": "read",
    "p": "AdvancedHunting.Read.All",
    "p_id": "7734e8e5-8dde-42fc-b5ae-6eafea078693",
    "p_fam": "AdvancedHunting",
    "ar_dn": "Run advanced hunting queries",
    "ar_dc": "Allows the app to run advanced hunting queries",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft Visual Studio Services API",
    "appDn": "c",
    "appId": "9bd5ab7f-4031-4045-ace9-6bebbad202f6",
    "p_type": "oa",
    "p_atype": "other",
    "p": "all",
    "p_id": "9bd5ab7f-4031-4045-ace9-6bebbad202f6",
    "p_fam": "all",
    "oa_aCsDn": "All",
    "oa_aCsDc": "Allow access to all serivce capabilities",
    "oa_uCsDn": "c",
    "oa_uCsDc": "This allows users to access all service capabilities",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Microsoft.Azconfig",
    "appDn": "Azure App Configuration",
    "appId": "35ffadb3-7fc1-497e-b61b-381d28e744cc",
    "p_type": "oa",
    "p_atype": "other",
    "p": "KeyValue.Delete",
    "p_id": "08eeff12-9b4a-4273-b3d9-ff8a13c32645",
    "p_fam": "KeyValue",
    "oa_aCsDn": "Delete Key-Values",
    "oa_aCsDc": "Allow the application to delete key-values on behalf of the signed-in user.",
    "oa_uCsDn": "Delete Key-Values As the Signed-In User",
    "oa_uCsDc": "Allow the application to delete key-values on your behalf.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Microsoft.Azure.SyncFabric",
    "appDn": "c",
    "appId": "00000014-0000-0000-c000-000000000000",
    "p_type": "oa",
    "p_atype": "write",
    "p": "Notifications.Write",
    "p_id": "0d7005c0-855a-485a-9d5b-5676f80a4a04",
    "p_fam": "Notifications",
    "oa_aCsDn": "Notifications.Write",
    "oa_aCsDc": "To allow application to send notifications to Azure AD provisioning service",
    "oa_uCsDn": " Send notifications to Azure AD provisioning service",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft.EventHubs",
    "appDn": "c",
    "appId": "80369ed6-5f11-4dd9-bef3-692475845e77",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "7d388411-3845-4cfc-aa69-33192f4b9735",
    "p_fam": None,
    "oa_aCsDn": "Have full access to the Azure Event Hub service",
    "oa_aCsDc": "Allow the application full access to the Azure Event Hubs service on behalf of the signed-in user",
    "oa_uCsDn": "Have full access to the Azure Event Hubs service",
    "oa_uCsDc": "Allow the application full access to the Azure Event Hubs service on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft.MileIQ.Dashboard",
    "appDn": "c",
    "appId": "f7069a8d-9edc-4300-b365-ae53c9627fc4",
    "p_type": "oa",
    "p_atype": "other",
    "p": "MileIQ.All",
    "p_id": "d26f02bb-ae28-4375-9184-101879252b0f",
    "p_fam": "MileIQ",
    "oa_aCsDn": "MileIQ.All",
    "oa_aCsDc": "MileIQ.All",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Microsoft.MileIQ.RESTService",
    "appId": "b692184e-b47f-4706-b352-84b288d2d9ee",
    "p_type": "ar",
    "p_atype": "read",
    "p": "MDLRest.Read",
    "p_id": "9b5904c8-49e7-4d21-81c0-118a2a9c7d81",
    "p_fam": "MDLRest",
    "ar_dn": "MDLRest.Read",
    "ar_dc": "Read Access To MDLRest APIs",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Microsoft.ServiceBus",
    "appDn": "c",
    "appId": "80a10ef9-8168-493d-abf9-3297c4ef6e3c",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "40e16207-c5fd-4916-8ca4-64565f2367ca",
    "p_fam": None,
    "oa_aCsDn": "Have full access to Azure Service Bus service",
    "oa_aCsDc": "Allow the application full access to the Azure Key Vault service on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Microsoft_Azure_Support",
    "appDn": "c",
    "appId": "959678cf-d004-4c22-82a6-d2ce549a58b8",
    "p_type": "oa",
    "p_atype": "other",
    "p": "SupportAndTroubleshootOperations.All",
    "p_id": "5f4c8442-eba3-4814-adca-42c6bb62590c",
    "p_fam": "SupportAndTroubleshootOperations",
    "oa_aCsDn": "Perform support operations for the user",
    "oa_aCsDc": "Allows the app to perform support operations on behalf of the user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "MicrosoftStorageExpressPodAADApp",
    "appId": "5613cb5c-a7c9-4099-8034-511fd7616cb2",
    "p_type": "ar",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "d6f965c1-8fd3-4bfd-b912-705922a79272",
    "p_fam": None,
    "ar_dn": "Azure Storage Express",
    "ar_dc": "Azure Storage Express service for customers to transfer large amount of data to their storage accounts using storage devices",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "MileIQ Admin Center",
    "appId": "de096ee1-dae7-4ee1-8dd5-d88ccc473815",
    "p_type": "ar",
    "p_atype": "other",
    "p": "mdladmincenterrole.admin",
    "p_id": "ea358ccf-c4a8-48ac-8b94-2558ae2f7a5c",
    "p_fam": "mdladmincenterrole",
    "ar_dn": "MDLAdminCenterRole.Admin",
    "ar_dc": "Business Admins who can use application",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "MRMaps PPE",
    "appDn": "c",
    "appId": "96636591-1bce-4eef-b8f9-939c0713889f",
    "p_type": "oa",
    "p_atype": "other",
    "p": "mixedreality.signin",
    "p_id": "326ee642-50a8-4c21-ba85-68887a9e84f3",
    "p_fam": "mixedreality",
    "oa_aCsDn": "mixedreality.signin",
    "oa_aCsDc": "This allows users to sign in to Spatial Maps",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "MRMapsProd",
    "appDn": "c",
    "appId": "af7c72b5-1a61-4bf3-958b-4e51e1ddfbe8",
    "p_type": "oa",
    "p_atype": "other",
    "p": "mixedreality.signin",
    "p_id": "b0c501aa-3640-456a-961e-7c302c78bc91",
    "p_fam": "mixedreality",
    "oa_aCsDn": "mixedreality.signin",
    "oa_aCsDc": "This allows users to sign in to Spatial Maps",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "MTP Unified RBAC",
    "appId": "9abd8443-d92a-40e6-a9ec-e5b6d29bc724",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Defender.RBAC.Read.All",
    "p_id": "1e95888a-4dde-464e-85df-8e8e7895a6f0",
    "p_fam": "Defender",
    "ar_dn": "Read all Defender RBAC and URBAC roles and permissions",
    "ar_dc": "Allows the app to read Defender RBAC and URBAC roles for a given identity.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "My Apps",
    "appDn": "c",
    "appId": "2793995e-0a7d-40d7-bd35-6968ba142197",
    "p_type": "oa",
    "p_atype": "read",
    "p": "workspace.read",
    "p_id": "f05e1490-846d-4ed2-abcf-869977a8a09f",
    "p_fam": "workspace",
    "oa_aCsDn": "workspace.read",
    "oa_aCsDc": "This allows users to read workspaces",
    "oa_uCsDn": "Read Workspace",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "AzureVirtualNetworkManager",
    "name": "Networking-MNC",
    "appId": "6d057c82-a784-47ae-8d12-ca7b38cf06b4",
    "p_type": "ar",
    "p_atype": "other",
    "p": "AzureEventGridSecureWebhook",
    "p_id": "c141600b-52f9-46b0-a3ad-5f3eb4890cc1",
    "p_fam": "AzureEventGridSecureWebhook",
    "ar_dn": "AzureEventGridSecureWebhook",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "O365 Demeter",
    "appId": "982bda36-4632-4165-a46a-9863b1bbcf7d",
    "p_type": "ar",
    "p_atype": "write",
    "p": "Transitions.ReadWrite",
    "p_id": "226ed26c-f1f6-46f4-8892-54c1d9569817",
    "p_fam": "Transitions",
    "ar_dn": "Transitions.ReadWrite",
    "ar_dc": "Allows apps to start and get status of transitions.",
    "csReq": "t",
    "crt": "critical",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "o365.servicecommunications.microsoft.com",
    "appId": "cb1bda4c-1213-4e8b-911a-0a8c83c5d3b7",
    "p_type": "ar",
    "p_atype": "other",
    "p": "PreAuthPlaceholder",
    "p_id": "25b4ea33-257e-47f5-b778-8df9c7e10548",
    "p_fam": "PreAuthPlaceholder",
    "ar_dn": "PreAuthPlaceholder",
    "ar_dc": "A placeholder scope for preauth",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "O365SBRM Service",
    "appDn": "c",
    "appId": "9d06afd9-66c9-49a6-b385-ea7509332b0b",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "9454efbe-3f0a-4074-9ec5-a25adefb6f87",
    "p_fam": None,
    "oa_aCsDn": "Have full access to the OCM Service ",
    "oa_aCsDc": "Allow the application full access to the OCM service on behalf of the signed-in user",
    "oa_uCsDn": "Have full access to the OCM service",
    "oa_uCsDc": "Allow the application full access to the OCM service on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Office 365 Exchange Online",
    "appId": "00000002-0000-0ff1-ce00-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Calendars.Read",
    "p_id": "798ee544-9d2d-430c-a058-570e29e34338",
    "p_fam": "Calendars",
    "ar_dn": "Read calendars in all mailboxes",
    "ar_dc": "Allows the app to read events of all calendars without a signed-in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Office 365 Information Protection",
    "appId": "2f3f02c9-5679-4a5c-a605-0de55b07d135",
    "p_type": "ar",
    "p_atype": "read",
    "p": "activitydata.tenant.read",
    "p_id": "ba4ca83c-e834-4e66-bfe1-df738f63b557",
    "p_fam": "activitydata",
    "ar_dn": "activitydata.tenant.read",
    "ar_dc": "c",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Office 365 Management APIs",
    "appId": "c5393580-f805-4401-95e8-94b7a6ef2fc2",
    "p_type": "ar",
    "p_atype": "read",
    "p": "ActivityFeed.Read",
    "p_id": "594c1fb6-4f81-4475-ae41-0c394909246c",
    "p_fam": "ActivityFeed",
    "ar_dn": "Read activity data for your organization",
    "ar_dc": "Allows the application to read activity data for your organization.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Office 365 SharePoint Online",
    "appId": "00000003-0000-0ff1-ce00-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Migration.Read.All",
    "p_id": "b7155856-e8b7-4ba1-bf43-8c9912353676",
    "p_fam": "Migration",
    "ar_dn": "Read access to migration data on the SharePoint admin site",
    "ar_dc": "Allows the app to read migration data via the SharePoint admin site without a signed-in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "M365PurvieweDiscoveryService",
    "name": "Office365 Zoom",
    "appId": "0d38933a-0bbd-41ca-9ebd-28c4b5ba7cb7",
    "p_type": "ar",
    "p_atype": "read",
    "p": "eDiscovery.Jobs.Read",
    "p_id": "0f062bc7-6f95-469a-810f-d846e6cbba44",
    "p_fam": "eDiscovery",
    "ar_dn": "eDiscovery.Jobs.Read",
    "ar_dc": "Allow app to read properties of jobs submitted to eDiscovery.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "OfficeClientService",
    "appDn": "c",
    "appId": "0f698dd4-f011-4d23-a33e-b36416dcb1e6",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "4003e653-ac3b-43c3-af2c-a49553838842",
    "p_fam": None,
    "oa_aCsDn": "user_impersonation",
    "oa_aCsDc": "Legacy scope used by Office Client",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "OneProfile Service",
    "appDn": "c",
    "appId": "b2cc270f-563e-4d8a-af47-f00963a71dcd",
    "p_type": "oa",
    "p_atype": "read",
    "p": "User.Read",
    "p_id": "6b0a3177-0946-453c-95bf-1d7b1886f0e4",
    "p_fam": "User",
    "oa_aCsDn": "Read user profiles",
    "oa_aCsDc": "Allows the app to read a set of the current user’s profile properties in your company or school. Includes display name, photo, and email address.",
    "oa_uCsDn": "Read your profile",
    "oa_uCsDc": "Allows the app to read a set of profile properties from your profile. Includes display name, photo, and email address.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "Policy Administration Service",
    "appDn": "c",
    "appId": "0469d4cd-df37-4d93-8a61-f8c75b809164",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "e1e4ebc7-1bb4-4ccc-8394-895d471ba1a7",
    "p_fam": None,
    "oa_aCsDn": "Have full access to the Microsoft Authorization Service",
    "oa_aCsDc": "Allow full access to the Microsoft Authorization Service on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow full access to the Microsoft Authorization Service on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Power BI Service",
    "appId": "00000009-0000-0000-c000-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Tenant.Read.All",
    "p_id": "654b31ae-d941-4e22-8798-7add8fdf049f",
    "p_fam": "Tenant",
    "ar_dn": "View all content in tenant",
    "ar_dc": "The app can view all content in the tenant without a signed in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Prod Messaging Catalog First Party App",
    "appDn": "c",
    "appId": "73bf035d-cf93-41d0-a8a9-f9407ce2e055",
    "p_type": "oa",
    "p_atype": "other",
    "p": "access_as_user",
    "p_id": "b9fa208e-7a07-49d9-9fe6-9ed353eec6c1",
    "p_fam": "access_as_user",
    "oa_aCsDn": "Access system data",
    "oa_aCsDc": "Allow the app to access resources on behalf of the signed-in user.",
    "oa_uCsDn": "Access resources",
    "oa_uCsDc": "Allow the app to access data on your behalf.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Purview Ecosystem",
    "appId": "9ec59623-ce40-4dc8-a635-ed0275b5d58a",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Purview.Activities.Upload.All",
    "p_id": "db90b932-4ee2-4549-8970-1932ef440310",
    "p_fam": "Purview",
    "ar_dn": "Call the UploadActivity API",
    "ar_dc": "Allows the app to call UploadActivity API.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Quota Core Service PROD",
    "appId": "d88dba5a-8fcb-4e07-b36c-7d148700f976",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Qs.Api.All",
    "p_id": "b77e1667-c4c2-4be1-ab53-cc94767800ad",
    "p_fam": "Qs",
    "ar_dn": "Call all Quota Service APIs",
    "ar_dc": "This allows applications to call Quota Service APIs",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Sherlock",
    "appDn": "c",
    "appId": "0e282aa8-2770-4b6c-8cf8-fac26e9ebe1f",
    "p_type": "oa",
    "p_atype": "other",
    "p": "Conversations.Access",
    "p_id": "1a8d204a-10fb-4da1-a303-17497f914fbc",
    "p_fam": "Conversations",
    "oa_aCsDn": "Access Sherlock Conversations API as organization users",
    "oa_aCsDc": "Allows the application to access Sherlock Conversations API acting as users in the organization.",
    "oa_uCsDn": "Access Sherlock Conversations API as you",
    "oa_uCsDc": "Allows the application to access Sherlock Conversations API as you.",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Signup",
    "appId": "b4bddae8-ab25-483e-8670-df09b9f1d0ea",
    "p_type": "ar",
    "p_atype": "other",
    "p": "ModernPostPurchaseProvisioning.Execute",
    "p_id": "8339ddc4-fc04-4ad0-b7d5-b7d83667da93",
    "p_fam": "ModernPostPurchaseProvisioning",
    "ar_dn": "ModernPostPurchaseProvisioning.Execute",
    "ar_dc": "Allows apps to call ModernPostPurchaseProvisioning API",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Skype for Business Online",
    "appId": "00000004-0000-0ff1-ce00-000000000000",
    "p_type": "ar",
    "p_atype": "other",
    "p": "Anonymous",
    "p_id": "b783bde8-ffc2-4f0c-96ce-6e2900b7aa4e",
    "p_fam": "Anonymous",
    "ar_dn": "Guest user join services (preview)",
    "ar_dc": "Allows the app create an on-demand Skype meeting and join guest users into Skype for Business services",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Targeted Messaging Service",
    "appDn": "c",
    "appId": "4c4f550b-42b2-4a16-93f9-fdb9e01bb6ed",
    "p_type": "oa",
    "p_atype": "read",
    "p": "user.read",
    "p_id": "42ac4dc0-0862-4f71-89ed-85c8dca034a4",
    "p_fam": "user",
    "oa_aCsDn": "user.read",
    "oa_aCsDc": "Allows reading basic user details",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "name": "TEST-Azure API Center",
    "appDn": "c",
    "appId": "a45c1cb0-6899-445e-8961-29576781c228",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "48f5e34f-bdfb-42e4-8da9-6519222a42ba",
    "p_fam": None,
    "oa_aCsDn": "Access Azure API Center Data API",
    "oa_aCsDc": "Allows access to the Azure API Center Data API service on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "TEST-SecurityPlatform",
    "appDn": "Sentinel Platform Services",
    "appId": "4500ebfb-89b6-4b14-a480-7f749797bfcd",
    "p_type": "oa",
    "p_atype": "other",
    "p": "SentinelPlatform.DelegatedAccess",
    "p_id": "991a963a-4203-4dbc-acf2-254a258f76f2",
    "p_fam": "SentinelPlatform",
    "oa_aCsDn": "Sentinel Platform Delegated API Access",
    "oa_aCsDc": "Allows the app to call the Sentinel Platform service APIs on behalf of a user.",
    "oa_uCsDn": "c",
    "oa_uCsDc": "c",
    "csReq": "f",
    "crt": "uc"
  },
  {
    "appDn": "c",
    "name": "Verifiable Credentials Service",
    "appId": "bb2a64ee-5d29-4b07-a491-25806dc854d3",
    "p_type": "ar",
    "p_atype": "other",
    "p": "VerifiedCredentials.TrustedIssuance",
    "p_id": "b4ebfa8b-750f-4993-8cf7-6a48fb98f13e",
    "p_fam": "VerifiedCredentials",
    "ar_dn": "VerifiedCredentials.TrustedIssuance",
    "ar_dc": "Enables the application to perform trusted issuance of verifiable credentials.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Verifiable Credentials Service Admin",
    "appId": "6a8b4b39-c021-437c-b060-5a14a3fd65f3",
    "p_type": "ar",
    "p_atype": "read",
    "p": "VerifiableCredential.Authority.Read",
    "p_id": "65499f04-0d5f-42ef-927e-6b4673fae3df",
    "p_fam": "VerifiableCredential",
    "ar_dn": "VerifiableCredential.Authority.Read",
    "ar_dc": "This allows the application to perform read operations on authorities via Admin API",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Verifiable Credentials Service Request",
    "appId": "3db474b9-6a0c-4840-96ac-1fceb342124f",
    "p_type": "ar",
    "p_atype": "create",
    "p": "VerifiableCredential.Create.All",
    "p_id": "949ebb93-18f8-41b4-b677-c2bfea940027",
    "p_fam": "VerifiableCredential",
    "ar_dn": "VerifiableCredential.Create.All",
    "ar_dc": "This allows the application to create Verifiable Credential issuance and presentation requests",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Windows 365",
    "appId": "0af06dc6-e4b5-4f28-818e-e78e62d137a5",
    "p_type": "ar",
    "p_atype": "other",
    "p": "CloudPC.PartnerReadWrite.All",
    "p_id": "c107831b-9c28-4609-b219-a7b3fc5cc190",
    "p_fam": "CloudPC",
    "ar_dn": "Partner read and write cloud pc",
    "ar_dc": "Allows the partner app to read and write the properties of Cloud PCs, without a signed-in user.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "Windows Azure Active Directory",
    "appId": "00000002-0000-0000-c000-000000000000",
    "p_type": "ar",
    "p_atype": "read",
    "p": "Application.Read.All",
    "p_id": "3afa6a7d-9b1a-42eb-948e-1650a849e176",
    "p_fam": "Application",
    "ar_dn": "Read all applications",
    "ar_dc": "Allows the app to read applications and service principals without a signed-in user",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "name": "Windows Azure Service Management API",
    "appDn": "Azure Resource Manager",
    "appId": "797f4846-ba00-4fd7-ba43-dac1f8f63013",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "41094075-9dad-400e-a0bd-54e686782033",
    "p_fam": None,
    "oa_aCsDn": "Access Azure Resource Manager as organization users",
    "oa_aCsDc": "Allows the application to access Azure Resource Manager acting as users in the organization.",
    "oa_uCsDn": "Access Azure Resource Manager as you",
    "oa_uCsDc": "Allows the application to access Azure Resource Manager as you.",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "name": "Windows Cloud Login",
    "appDn": "c",
    "appId": "270efc09-cd0d-444b-a71f-39af4910ec45",
    "p_type": "oa",
    "p_atype": "impersonation",
    "p": "user_impersonation",
    "p_id": "d0ee7be9-09ed-4def-83f2-6e72005521f7",
    "p_fam": None,
    "oa_aCsDn": "Sign in to Windows",
    "oa_aCsDc": "Allow the application to sign in to Windows on behalf of the signed-in user",
    "oa_uCsDn": "c",
    "oa_uCsDc": "Allow the application to sign in to Windows on your behalf",
    "csReq": "f",
    "crt": "critical"
  },
  {
    "appDn": "c",
    "name": "Windows Store for Business",
    "appId": "45a330b1-b1ec-4cc1-9161-9f03992aa49f",
    "p_type": "ar",
    "p_atype": "other",
    "p": "basicpurchaser",
    "p_id": "cf498509-9a5c-4d83-aa26-2b70fcbd0e1c",
    "p_fam": "basicpurchaser",
    "ar_dn": "Basic purchaser",
    "ar_dc": "Can buy products for inventory, assign and reclaim licenses.",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "Azure Virtual Desktop",
    "name": "Windows Virtual Desktop",
    "appId": "9cdead84-a844-4324-93f2-b2e6bb768d07",
    "p_type": "ar",
    "p_atype": "create",
    "p": "Tenant.Create",
    "p_id": "299dad25-58e3-473d-9733-171fb3034713",
    "p_fam": "Tenant",
    "ar_dn": "Tenant.Create",
    "ar_dc": "Creators can create Windows Virtual Desktop Tenants",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  },
  {
    "appDn": "c",
    "name": "WindowsDefenderATP",
    "appId": "fc780465-2017-40d4-a0c5-307022471b92",
    "p_type": "ar",
    "p_atype": "read",
    "p": "AdvancedQuery.Read.All",
    "p_id": "93489bf5-0fbc-4f2d-b901-33f2fe08ff05",
    "p_fam": "AdvancedQuery",
    "ar_dn": "Run advanced queries",
    "ar_dc": "Allows the app to run advanced queries",
    "csReq": "t",
    "crt": "uc",
    "APIAM_Ct": "uc",
    "APIAM_EAMTL": "uc"
  }
]